messages:
  noplayer: "&cVous devez être un joueur pour executer cette commande !"
  reload: "&7Configuration rechargee !"
  valorion:
    noonline: "&7Le joueur %player% n'est pas en ligne !"
    help:
      help: "&7Execution: &c/valorionpl help"
      help2: "&c/valorionpl help : &7Voir la liste des commandes"
      help3: "&c/valorionpl permissions help: &7Voir permissions commandes"
      help4: "&c/valorionpl reload : &7Reload la config Valorion"
      help5: "&c/sendplayerchat <joueur> <message>: &7Envoyer un message a un joueur"
      help6: "&c/getmat : &7Voir Type d'un item"
      help7: "&c/xpbottle : &7Convertir level en bottle xp"
    helpperms:
      help: "&c/valorionpl : &7valorion.permission.valorion"
      help2: "&c/valorionpl help : &7valorion.permission.valorion.help"
      help3: "&c/valorionpl permissions help : &7valorion.permission.valorion.getperms"
      help4: "&c/valorionpl reload : &7valorion.permission.valorion.reload"
      help5: "&c/sendplayerchat : &7pas de permission"
      help6: "&c/getmat : &7valorion.permission.getmat"
      help7: "&c/xpbottle : &7valorion.xpbottle"
  sendplayerchat:
    help: "&7Execution: &c/sendplayerchat <Joueur> <Message>"
  xpbottle:
    help: "&7Execution: &c/xpbottle [<level>]"
    helpgive: "&7Execution: &c/xpbotte give <level>"
    nonumber: "&cVeillez fournir un nombre valide !"
    nolevel: "&cVous n'avez pas assez de niveaux !"
    displayname: "&aBouteille d'xp - &c1 niveau"
    lore: "&2Faites un clique droit pour vous regive l'xp."


permissions:
  noperm: "&cTu n'as pas la permission d'executer cette commande !"
  bypasschat: "valorion.permission.cooldownbypass"
  valorion: "valorion.permission.valorion"
  valorionhelp: "valorion.permission.valorion.help"
  valorionreload: "valorion.permission.valorion.reload"
  valorionhelpperms: "valorion.permission.valorion.perms"
  getmat: "valorion.permission.getmat"
  xpbottle: "valorion.xpbottle"
  xpbottlegive: "valorion.xpbottle.give"
  rtp-teleport: "valorion.randomtp"
  rtp-sign-teleport: "valorion.randomtp.tpsign"
  rtp-sign-create: "valorion.randomtp.createsign"

# TRUE = PORTAL ACTIVER - FALSE = PORTAL DESACTIVE
# enter-on-portail s'applique qu'au portails de l'end et du nether
portals:
  #Nether
  create-nether: false
  enter-nether: false
  #End
  create-end: false
  enter-end: false
  #Others
  create-aether: false