name: ValorionPlugin
version: 1.0.3
main: fr.volax.valorionplugin.Main
description: Valorion Plugin
author: Volax
commands:
  sendplayerchat:
    description: Pour envoyer un message avec des couleurs
  valorionpl:
    description: Commande principal du plugin Valorion
  getmat:
    description: Pour avoir le getType de l'item ( Pour le plugin Faction )
  xpbottle:
    description: Transformer l'xp en bouteille
  ec:
    description: Convertisseur customec open en ec